name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Lint
        run: |
          cd server
          npm run lint

      - name: Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
